name: Helm Publish

on:
  push:
    tags: [ '[0-9]+.[0-9]+.[0-9]+-*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Exit if not on main branch
        if: endsWith(github.ref, 'main') == false
        run: exit -1
      
      - name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"

          CHART_NAME=$(echo $GITHUB_REF_NAME | cut -d '-' -f2-)
          CHART_VERSION=$(echo $GITHUB_REF_NAME | cut -d '-' -f-1)

          echo "CHART_NAME=${CHART_NAME}" >> $GITHUB_ENV
          echo "CHART_VERSION=${CHART_VERSION}" >> $GITHUB_ENV

      - name: GitHub Tag echo example
        run: |
          echo $CHART_NAME
          echo $CHART_VERSION
