name: Helm Publish

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  CHART_NAME: data-platform-cluster
  CHART_IMAGE: CHART_IMAGE=ghcr.io/${{ github.repository_owner }}/${CHART_NAME}
  CHART_VERSION: 0.0.1
jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Helm
        uses: Azure/setup-helm@v1
        with:
          version: v3.11.1

      - name: Helm Lint
        run: |
          helm lint ${CHART_NAME} --values ${CHART_NAME}/values.yaml

      - name: Helm Template
        run: |
          helm template ${CHART_NAME} --values ${CHART_NAME}/values.yaml

      - name: Helm Package
        run: |
          helm package ${CHART_NAME}/ ${CHART_IMAGE}:${CHART_VERSION}
